apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: openweather-secret-aws
  namespace: app
spec:
  provider: aws
  secretObjects:
  - data: 
    - key: OPENWEATHER_APIKEY
      objectName: openweather-secrets
    - key: APIKEYS
      objectName: openweather-secrets
    secretName: openweather-secret-aws
    type: Opaque
  parameters:
    objects: |
      - objectName: openweather-secrets
        objectType: secretsmanager
        objectAlias: openweather-secrets